apiVersion: v1
kind: Service
metadata:
  name: webhook-server-internal
spec:
  selector:
    app: webhook-server
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP   # default, for internal-only communication